# -*- coding: utf-8 -*-
from enum import Enum
from typing import Any


class MeariErrorCode(Enum):
    """Meari error code."""
    # Base error code
    CODE_UNKNOWN = 1000

    # General error codes
    REQUEST_SUCCESSFUL = 1001
    REQUEST_FAILED = 1002
    INVALID_PARAMETER = 1003
    INVALID_VERIFICATION_CODE = 1004
    SYSTEM_EXCEPTION = 1005
    DATABASE_EXCEPTION = 1006
    DATA_NOT_EXIST = 1007
    VERIFICATION_CODE_ERROR = 1008
    VERIFICATION_CODE_EXPIRED = 1009
    ALREADY_A_FRIEND = 1010
    MESSAGE_WAITING_PROCESS = 1011
    PROCESSING_SUCCESSFUL = 1012
    DEVICE_ADDED_BY_OTHER = 1013
    NO_UNREAD_MESSAGES = 1014
    UNREAD_MESSAGES_EXIST = 1015
    DEVICE_SHARED_DUPLICATED = 1016
    INCORRECT_LOGIN_PASSWORD = 1017
    USER_ACCOUNT_NOT_EXIST = 1018
    USER_ACCOUNT_ALREADY_EXISTS = 1019
    PASSWORD_CORRECT = 1020
    DEVICE_SHARED = 1021
    ADD_FRIEND_OWN_ACCOUNT = 1022
    INVALID_USER_TOKEN_SIGNATURE = 1023
    PROCESS_MESSAGE = 1024
    PAYMENT_AMOUNT_CALCULATION_ERROR = 1025
    ORDER_TIMEOUT = 1026
    ORDER_DATA_ERROR = 1027
    UNPAID = 1028
    CANNOT_TRY_AGAIN = 1029
    USER_DEVICE_MISMATCH = 1030
    MAILBOX_NOT_EXIST = 1031
    NVR_BIND_CAMERA_LIMIT = 1032
    INVALID = 1033
    CANNOT_GET_DST = 1038
    SMS_SENDING_FAILED = 1039
    NOT_A_FRIENDSHIP = 1040
    INVALID_GRAFFITI_TOKEN = 1041
    INVALID_1042 = 1042
    DOORBELL_NOT_STOLEN = 1046
    DOORBELL_STOLEN = 1045
    DOORBELL_ANSWERED_CANNOT_HANGUP = 1047
    ACCOUNT_REGISTERED_OTHER_REGION = 1048
    DEVICE_NOT_BOUND = 1049
    INVALID_SHARE_RELATIONSHIP = 1050
    REPEATED_ORDER_PAYMENT = 1051
    ORDER_PAYMENT_FAILED = 1052
    FRIENDS_SHARE_SUCCESS = 1055
    FACTORY_AUTH_FAILED = 1057
    OLD_IOTHUB_PROCESS_FAILED = 1058
    DEVICE_ADDED_BY_SELF = 1059
    INVALID_IP_ADDRESS = 1062
    INVALID_1064 = 1064
    SETUP_FAILED = 1066
    CLOUD_STORAGE_CODE_USED = 1067
    INVALID_CLOUD_STORAGE_CODE = 1068
    DEVICE_SHARE_TO_SELF = 1069
    RELAY_DEVICE_NOT_EXIST = 1070
    STRONGLY_BOUND_RESELLER = 1071
    RELAY_SUB_DEVICE_LIMIT_EXCEEDED = 1072
    RELAY_ADD_RESTRICTION_LOCK = 1073
    INVALID_1074 = 1074

    # Family-related errors
    DEFAULT_FAMILY_CANNOT_BE_DELETED = 1101
    FAMILY_NOT_EXIST = 1102
    ROOM_NOT_EXIST = 1103
    DEVICE_NOT_IN_ROOM = 1104
    FAMILY_MEMBER_ALREADY_EXISTS = 1105
    NO_PERMISSIONS_NOT_FAMILY_OWNER = 1106
    USER_IS_HOME_OWNER = 1107
    REQUEST_SUCCESS_WAITING_PROCESS = 1108
    MESSAGE_PROCESSED = 1109
    NUMBER_REACHED_LIMIT = 1110
    MEMBER_NO_LONGER_IN_FAMILY = 1111
    NOT_AUTHORIZED_FAMILY_MESSAGE = 1113
    FAMILY_NAME_ALREADY_EXISTS = 1114
    DEVICE_NOT_ACTIVATED_4G = 1150
    MAILBOX_ALREADY_BOUND = 1191
    ACCOUNT_NOT_SUPPORT_MIGRATION = 1195

    # Device-related errors
    ADD_DEVICE_INVALID_UUID = 2001
    ADD_DEVICE_EMPTY_P2P_INFO = 2002
    ADD_DEVICE_NO_P2P_NUMBER = 2003
    ADD_DEVICE_FAILED_GET_IOT_INFO = 2004
    ADD_DEVICE_FAILED = 2005
    ADD_DEVICE_VERIFICATION_FAILED = 2006
    ADD_DEVICE_LICENSE_NOT_EXIST = 2007
    ADD_DEVICE_NO_MAC_VERIFICATION_DATA = 2008
    ADD_DEVICE_NOT_FACTORY_CERTIFIED_MAC_CONFLICT = 2009


class MeariError(Exception):
    """Meari error."""
    code: MeariErrorCode
    message: Any

    def __init__(
        self,  message: Any, code: MeariErrorCode = MeariErrorCode.CODE_UNKNOWN
    ) -> None:
        self.message = message
        self.code = code
        super().__init__(self.message)

    def to_str(self) -> str:
        return f'{{"code":{self.code.value},"message":"{self.message}"}}'

    def to_dict(self) -> dict:
        return {"code": self.code.value, "message": self.message}


class MeariAuthError(MeariError):
    ...


class MeariHttpError(MeariError):
    ...
